Add Calendar class
sillsdev/icu-dotnet pull request #111
Opened 2019-03-21 09:09 UTC by j-troc

2019-03-21 11:40 UTC, ermshiperete commented
Just a quick question before I dig deeper into the code review: 

What benefits does the ICU calendar class give over just using .NET's [Calendar](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.calendar) class?

2019-03-21 11:50 UTC, ermshiperete commented
The PR fails two tests on Linux in the CI build:

```
1) Failed : Icu.Tests.CalendarTests.GetTimeZoneTest
  Expected string length 30 but was 13. Strings differ at index 0.
  Expected: "Central European Standard Time"
  But was:  "Europe/Zagreb"
  -----------^

2) error : Icu.Tests.CalendarTests.SetTimeZone2Test [/home/jenkins/workspace/icu-dotnet_PR-111/build/icu-dotnet.proj]
System.TimeZoneNotFoundException : The time zone ID 'Romance Standard Time' was not found on the local computer.
  ----> System.IO.FileNotFoundException : Could not find file '/usr/share/zoneinfo/Romance Standard Time'.
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at Icu.Tests.CalendarTests.SetTimeZone2Test() in /home/jenkins/workspace/icu-dotnet_PR-111/source/icu.net.tests/CalendarTests.cs:line 361
--FileNotFoundException
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Internal.IO.File.ReadAllBytes(String path)
   at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(String id, TimeZoneInfo& value, Exception& e)
```

2019-03-26 11:22 UTC, ermshiperete requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/111)* status: all files reviewed, 19 unresolved discussions (waiting on @j-troc)

___
*[source/icu.net/Calendar/Calendar.cs, line 157 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LaUmIzs91HElGKBbHb7:-LaUmIzs91HElGKBbHb8:b62tsw8) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/Calendar.cs#L157)):*
> ```Smalltalk
> 		protected Locale _locale;
> 
> 		
> ```

nitpick: extra whitespace
___
*[source/icu.net/Calendar/Calendar.cs, line 193 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LaUzVC_7PKvD6tUSH0S:-LaUzVC_7PKvD6tUSH0T:bxzmelh) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/Calendar.cs#L193)):*
> ```Smalltalk
> 		/// <param name="dateTime">The given date in UTC (GMT) time.</param>
> 		public void SetTime(DateTime dateTime)
> 		{
> ```

It might make sense to work with `dateTime.ToUniversalTime()`, then the date can be in any timezone.
___
*[source/icu.net/Calendar/Calendar.cs, line 227 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-Lao9vp52QXeRHNJLkRr:-Lao9vp52QXeRHNJLkRs:bduclem) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/Calendar.cs#L227)):*
> ```Smalltalk
> 		/// 
> 		/// The only difference between roll() and add() is that roll() does not change the value of more significant fields
> 		/// when it reaches the minimum or maximum of its range, whereas add() does.
> ```

It might be helpful to add a unit test that demonstrates the difference between the two methods.
___
*[source/icu.net/Calendar/Calendar.cs, line 464 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LaoDtvg53-156f5whNT:-LaoDtvg53-156f5whNU:bezz4da) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/Calendar.cs#L464)):*
> ```Smalltalk
> 			set
> 			{
> 				NativeMethods.ucal_setAttribute(_calendarHandle, UCalendarAttribute.FirstDayOfWeek, value);
> ```

Shouldn't this be `UCalendarAttribute.MinimalDaysInFirstWeek`?!
___
*[source/icu.net/Calendar/Calendar.cs, line 507 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LaoEGZR5VAeqcDss9tv:-LaoEGZR5VAeqcDss9tw:bpmjg34) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/Calendar.cs#L507)):*
> ```Smalltalk
> 			get
> 			{
> 				return NativeMethods.ucal_get(_calendarHandle, UCalendarDateFields.Era, out _);
> ```

Check error? (same for the other uses of `ucal_get`)
___
*[source/icu.net/Calendar/Calendar.cs, line 646 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LatiF504CQJLVLShTAo:-LatiF504CQJLVLShTAp:bc38sgv) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/Calendar.cs#L646)):*
> ```Smalltalk
> 		/// Gets or seths whether the hour is before or after noon.
> 		/// </summary>
> 		public int AmPm
> ```

Wouldn't it be better to use `bool` as return value here?
___
*[source/icu.net/Calendar/Calendar.cs, line 806 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LaoEnSs8MQLdH3lhYHr:-LaoEnSs8MQLdH3lhYHs:bc64ztu) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/Calendar.cs#L806)):*
> ```
> _calendarHandle.Dispose();
> ```

This should go in the `if (disposing)` block. In the case of `disposing` being `false` the GC takes care of calling dispose on the calendar handle.
___
*[source/icu.net/Calendar/Calendar.cs, line 807 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LaoEt_89b0fVPYKYCy1:-LaoEt_89b0fVPYKYCy2:b-4gguw9) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/Calendar.cs#L807)):*
> ```
> _disposingValue = true
> ```

There seems to be a mismatch between the name and intention of the variable and what it does. If you want to detect redundant calls then you'd have to set it to `true` right after `if (!_disposingValue)` and to `false` before leaving the block. The way it is currently used checks whether or not the object is already disposed - a better name name would then be `_isDisposed`.
___
*[source/icu.net/Calendar/GregorianCalendar.cs, line 40 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LaUx6ui4aC8EDEII94n:-LaUx6ui4aC8EDEII94o:bz0ggfa) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/GregorianCalendar.cs#L40)):*
> ```Smalltalk
> 		{
> 			var handle = NativeMethods.ucal_clone(_calendarHandle, out ErrorCode status);
> 			return new GregorianCalendar(handle);
> ```

We should probably copy `_locale` as well. 

Error checking?
___
*[source/icu.net/Calendar/GregorianCalendar.cs, line 45 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LaUxehU1HPXRwEpOQVP:-LaUxehU1HPXRwEpOQVQ:blzshg6) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/Calendar/GregorianCalendar.cs#L45)):*
> ```Smalltalk
> 		public override bool InDaylightTime()
> 		{
> 			return NativeMethods.ucal_inDaylightTime(_calendarHandle, out _);
> ```

We should probably do some error checking, otherwise returning `false` can mean _not in daylight savings time_ AND _something went wrong_ which makes it hard to debug in a client app.
___
*[source/icu.net/NativeMethods/NativeMethods_Calendar.cs, line 76 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LaoDIuo1FIYG7plmGAZ:-LaoDIupBy2LWJu7hiBd:bk8tah6) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/NativeMethods/NativeMethods_Calendar.cs#L76)):*
> ```Smalltalk
> 
> 			[UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Unicode)]
> 			internal delegate int ucal_getAttributeDelegate(
> ```

Strange that you have it with three parameters here - the [docs](http://icu-project.org/apiref/icu4c/ucal_8h.html#ae38dffa3217680e56e30e5d1bca673ab) list only two. Are you sure this is correct?

If this is correct a unit test would be good that proves that this is the correct/working signature (and even if this wrong a unit test would be nice...)
___
*[source/icu.net/NativeMethods/NativeMethods_Calendar.cs, line 185 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LatWxgG6gz7GnMcS3AP:-LatWxgG6gz7GnMcS3AQ:b-169b5r) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/NativeMethods/NativeMethods_Calendar.cs#L185)):*
> ```
> out string result,
> ```

I'd prefer if you change this to `IntPtr result` and deal with converting to a string in the wrapper method. See for example `Normalizer2.GetDecomposition` and `unorm2_getDecomposition` in `NativeMethods_Normalize.cs`.

This would be more in alignment of the way it's done elsewhere in icu.net.
___
*[source/icu.net/NativeMethods/NativeMethods_Calendar.cs, line 237 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LatULvfAtplbXd4v_Qx:-LatULvfAtplbXd4v_Qy:bcdgd7y) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/NativeMethods/NativeMethods_Calendar.cs#L237)):*
> ```Smalltalk
> 		}
> 		public static void ucal_roll(
> 		Calendar.SafeCalendarHandle cal,
> ```

nitpick: indentation
___
*[source/icu.net/NativeMethods/NativeMethods_Calendar.cs, line 322 at r1](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-LatW6ya8towZy0FlkIC:-LatW6ya8towZy0FlkID:bepjgg3) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6ea62b70e7d00530eea24703b3cd97b370ae3c43/source/icu.net/NativeMethods/NativeMethods_Calendar.cs#L322)):*
> ```
> out string result
 [...]

2020-02-24 12:07 UTC, sillsdevgerrit commented
A team member has to approve this pull request on the CI server before it can be built...

2020-02-25 11:29 UTC, ermshiperete requested changes
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/111)* status: 1 of 4 files reviewed, 15 unresolved discussions (waiting on @ermshiperete and @j-troc)

___
*[source/icu.net.tests/CalendarTests.cs, line 275 at r2](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M0w1D4LBT9Z2ex9IEVk:-M0w1D4LBT9Z2ex9IEVl:b9xp1zn) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6994ae91d1e9ef36e2513b815943a012573bc891/source/icu.net.tests/CalendarTests.cs#L275)):*
> ```Smalltalk
> 				var val1 = cal.FirstDayOfWeek;
> 
> 				Assert.AreEqual(Calendar.UCalendarDaysOfWeek.Sunday, val0);
> ```

Please write this as separate tests. You can use the `TestCase` attribute for that. See below.
___
*[source/icu.net.tests/CalendarTests.cs, line 294 at r2](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M0w18xO7YhtAcazXs0u:-M0w18xO7YhtAcazXs0v:b9xp1zn) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6994ae91d1e9ef36e2513b815943a012573bc891/source/icu.net.tests/CalendarTests.cs#L294)):*
> ```Smalltalk
> 
> 
> 				Assert.AreEqual(2, val0);
> ```

Please write this as separate tests. You can use the `TestCase` attribute for that. See below.
___
*[source/icu.net.tests/CalendarTests.cs, line 312 at r2](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M0w11tIDQz8OQuwmXhO:-M0w11tIDQz8OQuwmXhP:b9xp1zn) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6994ae91d1e9ef36e2513b815943a012573bc891/source/icu.net.tests/CalendarTests.cs#L312)):*
> ```Smalltalk
> 				var val1 = cal.WeekOfYear;
> 
> 				Assert.AreEqual(2, val0);
> ```

Please write this as separate tests. You can use the `TestCase` attribute for that. See below.
___
*[source/icu.net.tests/CalendarTests.cs, line 395 at r2](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M0w0s8a5bTp7-UYTMyQ:-M0w0s8a5bTp7-UYTMyR:b9xp1zn) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6994ae91d1e9ef36e2513b815943a012573bc891/source/icu.net.tests/CalendarTests.cs#L395)):*
> ```Smalltalk
> 				var val1 = cal.WeekOfMonth;
> 
> 				Assert.AreEqual(2, val0);
> ```

Please write this as separate tests. You can use the `TestCase` attribute for that. See below.
___
*[source/icu.net.tests/CalendarTests.cs, line 409 at r2](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M0w0njM8iSivvegKRMu:-M0w0njM8iSivvegKRMv:b9xp1zn) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6994ae91d1e9ef36e2513b815943a012573bc891/source/icu.net.tests/CalendarTests.cs#L409)):*
> ```Smalltalk
> 				var era0 = cal.Era;
> 
> 				Assert.AreEqual(1, era1);
> ```

Please write this as separate tests. You can use the `TestCase` attribute for that. See below.
___
*[source/icu.net.tests/CalendarTests.cs, line 445 at r2](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M0w0hj84oFnTvKLw9ug:-M0w0hj84oFnTvKLw9uh:b-9y7xlw) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6994ae91d1e9ef36e2513b815943a012573bc891/source/icu.net.tests/CalendarTests.cs#L445)):*
> ```Smalltalk
> 				var offset1 = cal.DstOffset;
> 
> 				Assert.AreEqual(expected0, offset0);
> ```

Please write this as separate tests. You can use the `TestCase` attribute for that:

```C#
		[TestCase(Calendar.UCalendarMonths.July,    ExpectedResult = 3600000 /* 60min * 60s * 1000ms */)]
		[TestCase(Calendar.UCalendarMonths.January, ExpectedResult = 0)]
		public int DstOffsetTest(Calendar.UCalendarMonths month)
		{
			var zone = new TimeZone("Europe/Paris");

			using (var cal = new GregorianCalendar(zone))
			{
				cal.Month = month;
				cal.DayOfMonth = 20;

				return cal.DstOffset;
			}
		}
```
___
*[source/icu.net.tests/CalendarTests.cs, line 460 at r2](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M0w-f187aswnsTkibRI:-M0w-f187aswnsTkibRJ:b-eaidep) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6994ae91d1e9ef36e2513b815943a012573bc891/source/icu.net.tests/CalendarTests.cs#L460)):*
> ```Smalltalk
> 				var val1 = cal.AmPm;
> 
> 				Assert.AreEqual(Calendar.UCalendarAMPMs.Am, val0);
> ```

Please write this as separate tests. You can use the `TestCase` attribute for that:

```C#
		[TestCase( 3, ExpectedResult = Calendar.UCalendarAMPMs.Am)]
		[TestCase(14, ExpectedResult = Calendar.UCalendarAMPMs.Pm)]
		public Calendar.UCalendarAMPMs AmPmTest(int hourOfDay)
		{
			using (var cal = new GregorianCalendar(new TimeZone("UTC")))
			{
				cal.HourOfDay = hourOfDay;
				return cal.AmPm;
			}
		}
```
___
*[source/icu.net.tests/CalendarTests.cs, line 474 at r2](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M0w--meD7k4cmas482n:-M0w--meD7k4cmas482o:bwpjdc7) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6994ae91d1e9ef36e2513b815943a012573bc891/source/icu.net.tests/CalendarTests.cs#L474)):*
> ```Smalltalk
> 
> 			var timezone = timezones.FirstOrDefault(tzi => tzi.Id == tzdbId);
> 			if(timezone==null)
> ```

Please create two separate tests, one for Windows and the other for Linux. You can use `[Platform(Exclude="win")]` and `[Platform(Include="win")]` to have them run only on one platform.
___
*[source/icu.net.tests/CalendarTests.cs, line 501 at r2](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M0vxi9d56MYFaVbyNe-:-M0vxi9d56MYFaVbyNe0:bwpjdc7) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/6994ae91d1e9ef36e2513b815943a012573bc891/source/icu.net.tests/CalendarTests.cs#L501)):*
> ```Smalltalk
> 				var result = cal.GetTimeZoneInfo();
> 
> 				Assert.IsTrue(result.Id == winId || result.Id == tzdbId);
> ```

Please create two separate tests, one for Windows and the other for Linux. You can use `[Platform(Exclude="win")]` and `[Platform(Include="win")]` to have them run only on one platform.


<!-- Sent from Reviewable.io -->

2020-02-25 15:45 UTC, sillsdevgerrit commented
A team member has to approve this pull request on the CI server before it can be built...

2020-02-25 17:28 UTC, sillsdevgerrit commented
A team member has to approve this pull request on the CI server before it can be built...

2020-02-26 10:54 UTC, ermshiperete requested changes
> Reviewed 2 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/icu-dotnet/111)* status: all files reviewed, 4 unresolved discussions (waiting on @j-troc)

___
*[source/icu.net.tests/CalendarTests.cs, line 473 at r3](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M103fMd2wWoG5kZ6rP6:-M103fMeAOCgRfpGA1vm:bqkrhci) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a993b39bebab5534c97047d0e58dc169e6926b77/source/icu.net.tests/CalendarTests.cs#L473)):*
> ```Smalltalk
> 		[Test]
> 		[Platform(Include = "win")]
> 		public void GetTilmeZoneInfoTestWin()
> ```

Typo: should be `GetTimeZoneInfoTestWin`
___
*[source/icu.net.tests/CalendarTests.cs, line 481 at r3](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M103sTW22B0wNuhEfO4:-M103sTW22B0wNuhEfO5:b4u1koc) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a993b39bebab5534c97047d0e58dc169e6926b77/source/icu.net.tests/CalendarTests.cs#L481)):*
> ```Smalltalk
> 				var result = cal.GetTimeZoneInfo();
> 
> 				Assert.IsTrue(result.Id == "Central European Standard Time");
> ```

Would be better written as `Assert.AreEqual("Central European Standard Time", result.Id)` or `Assert.That(result.Id, Is.EqualTo("Central European Standard Time"))`
___
*[source/icu.net.tests/CalendarTests.cs, line 497 at r3](https://reviewable.io/reviews/sillsdev/icu-dotnet/111#-M105dVQBdh6GQ0xs9TZ:-M105dVQBdh6GQ0xs9T_:b-34vmyd) ([raw file](https://github.com/sillsdev/icu-dotnet/blob/a993b39bebab5534c97047d0e58dc169e6926b77/source/icu.net.tests/CalendarTests.cs#L497)):*
> ```Smalltalk
> 				var result = cal.GetTimeZoneInfo();
> 
> 				Assert.IsTrue(result.Id == tzdbId);
> ```

See above


<!-- Sent from Reviewable.io -->

2020-02-26 12:33 UTC, sillsdevgerrit commented
A team member has to approve this pull request on the CI server before it can be built...

2020-03-05 08:39 UTC, j-troc commented
It builds just fine on my machines.

2020-03-05 08:51 UTC, ermshiperete commented
> It builds just fine on my machines.

Did you try on Linux? From the build logs it looks like it gets some memory corruption - possibly the signature for an unmanaged method isn't quite correct yet. 

```
...
[2020-02-26T13:20:41.725Z]   => Icu.Tests.ResourceBundleTests.IsNull
[2020-02-26T13:20:41.725Z]   => Icu.Tests.ResourceBundleTests.Name
[2020-02-26T13:20:41.725Z]   => Icu.Tests.TimeZoneTests.GetCountryTimeZonesTest
[2020-02-26T13:20:41.725Z]   => Icu.Tests.TimeZoneTests.GetDefaultTimeZoneTest
[2020-02-26T13:20:42.288Z] /home/jenkins/workspace/icu-dotnet_PR-111/build/icu-dotnet.proj(96,3): warning : 
[2020-02-26T13:20:42.288Z] /home/jenkins/workspace/icu-dotnet_PR-111/build/icu-dotnet.proj(96,3): warning : =================================================================
[2020-02-26T13:20:42.288Z] /home/jenkins/workspace/icu-dotnet_PR-111/build/icu-dotnet.proj(96,3): warning : 	External Debugger Dump:
[2020-02-26T13:20:42.288Z] /home/jenkins/workspace/icu-dotnet_PR-111/build/icu-dotnet.proj(96,3): warning : ================================================================
[2020-02-26T13:20:42.288Z] /home/jenkins/workspace/icu-dotnet_PR-111/build/icu-dotnet.proj(96,3): warning : mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
[2020-02-26T13:20:42.288Z]   
[2020-02-26T13:20:42.288Z]   =================================================================
[2020-02-26T13:20:42.288Z]   	Basic Fault Address Reporting
[2020-02-26T13:20:42.288Z]   =================================================================
[2020-02-26T13:20:42.288Z]   Memory around native instruction pointer (0x7f7f521f4d72):0x7f7f521f4d62  ac 24 38 21 05 d8 1d 31 10 ae 94 1b 18 3e 31 37  .$8!...1.....>17
[2020-02-26T13:20:42.288Z]   0x7f7f521f4d72  00 15 31 2b 00 3a 21 15 14 3a 15 3c 2c 38 21 10  ..1+.:!..:.<,8!.
[2020-02-26T13:20:42.288Z]   0x7f7f521f4d82  2c 20 01 01 da 6f fa 15 14 2d 2f 04 3a 38 21 04  , ...o...-/.:8!.
[2020-02-26T13:20:42.288Z]   0x7f7f521f4d92  00 36 01 d8 1b 26 10 b2 c1 15 d2 c0 21 11 15 3a  .6...&......!..:
[2020-02-26T13:20:42.288Z]   
[2020-02-26T13:20:42.288Z]   =================================================================
[2020-02-26T13:20:42.288Z]   	Managed Stacktrace:
[2020-02-26T13:20:42.288Z]   =================================================================
[2020-02-26T13:20:42.288Z]   	  at <unknown> <0xffffffff>
[2020-02-26T13:20:42.288Z]   	  at System.Object:wrapper_native_0x7f7f521f4d70 <0x00096>
[2020-02-26T13:20:42.288Z]   	  at Icu.NativeMethods:ucal_getDefaultTimeZone <0x000c0>
[2020-02-26T13:20:42.288Z]   	  at <>c:<GetDefault>b__9_0 <0x0003f>
[2020-02-26T13:20:42.288Z]   	  at Icu.NativeMethods:GetString <0x0007d>
[2020-02-26T13:20:42.288Z]   	  at Icu.NativeMethods:GetUnicodeString <0x00033>
[2020-02-26T13:20:42.288Z]   	  at Icu.TimeZone:GetDefault <0x00103>
[2020-02-26T13:20:42.288Z]   	  at Icu.Tests.TimeZoneTests:GetDefaultTimeZoneTest <0x00057>
[2020-02-26T13:20:42.288Z]   	  at System.Object:runtime_invoke_void__this__ <0x00085>
[2020-02-26T13:20:42.288Z]   	  at <unknown> <0xffffffff>
[2020-02-26T13:20:42.288Z]   	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x000d0>
[2020-02-26T13:20:42.288Z]   	  at System.Reflection.RuntimeMethodInfo:Invoke <0x00142>
[2020-02-26T13:20:42.288Z]   	  at System.Reflection.MethodBase:Invoke <0x00045>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Reflect:InvokeMethod <0x00092>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.MethodWrapper:Invoke <0x0003b>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Commands.TestMethodCommand:InvokeTestMethod <0x00066>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Commands.TestMethodCommand:RunTestMethod <0x00177>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Commands.TestMethodCommand:Execute <0x00033>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.SimpleWorkItem:PerformWork <0x00057>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.WorkItem:RunOnCurrentThread <0x00118>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.WorkItem:Execute <0x001f3>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher:Dispatch <0x0012f>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher:Dispatch <0x0003f>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.CompositeWorkItem:RunChildren <0x002f5>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.CompositeWorkItem:PerformWork <0x0017f>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.WorkItem:RunOnCurrentThread <0x00118>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.WorkItem:Execute <0x001f3>
[2020-02-26T13:20:42.288Z]   	  at NUnit.Framework.Internal.Execution.TestWorker:TestWorkerThreadProc <0x001fa>
[2020-02-26T13:20:42.288Z]   	  at System.Threading.ThreadHelper:ThreadStart_Context <0x000a5>
[2020-02-26T13:20:42.288Z]   	  at System.Threading.ExecutionContext:RunInternal <0x0021d>
[2020-02-26T13:20:42.288Z]   	  at System.Threading.ExecutionContext:Run <0x00052>
[2020-02-26T13:20:42.288Z]   	  at System.Threading.ExecutionContext:Run <0x00072>
[2020-02-26T13:20:42.288Z]   	  at System.Threading.ThreadHelper:ThreadStart <0x00052>
[2020-02-26T13:20:42.288Z]   	  at System.Object:runtime_invoke_void__this__ <0x00085>
[2020-02-26T13:20:42.288Z]   =================================================================
[2020-02-26T13:20:42.288Z]   
[2020-02-26T13:20:42.288Z]   Errors, Failures and Warnings
[2020-02-26T13:20:42.288Z]   
[2020-02-26T13:20:42.288Z]   1) Error : 
...
```

(Note that `GetDefaultTimeZoneTest` isn't necessarily the test that's causing the problems)

2020-03-11 14:14 UTC, sillsdevgerrit commented
A team member has to approve this pull request on the CI server before it can be built...

2020-03-12 13:34 UTC, sillsdevgerrit commented
A team member has to approve this pull request on the CI server before it can be built...

2020-04-01 14:01 UTC, sillsdevgerrit commented
A team member has to approve this pull request on the CI server before it can be built...

2020-04-02 13:34 UTC, sillsdevgerrit commented
A team member has to approve this pull request on the CI server before it can be built...

2025-02-20 16:09 UTC, imnasnainaec commented
@j-troc @ermshiperete Is this worth completing?

2026-05-26 19:14 UTC, imnasnainaec commented
@ermshiperete At this point, should we just close?

2026-05-27 07:46 UTC, ermshiperete commented
@imnasnainaec Yes, seems reasonable

2026-05-27 07:46 UTC, closed without merging