Update copyright date and "SIL International→Global"
sillsdev/icu-dotnet pull request #205
Opened 2024-10-01 19:29 UTC by merchako

2024-10-01 19:49 UTC, lyonsil commented
Why just this one file? There are 111 matches of "SIL International" is the *.cs files from what I see at `grep -r --include="*.cs" "SIL International" | wc -l`.

2024-10-01 19:49 UTC, imnasnainaec requested changes
A search for "international" in this repo (https://github.com/search?q=repo%3Asillsdev%2Ficu-dotnet+International&type=code) shows many other copyright statements that also need to be updated.

2024-10-02 21:07 UTC, merchako commented
Yeah, maybe we just leave it then. I was just passing by and saw the need to change. Trying to get more comfortable making commits and PRs.

2024-10-03 13:04 UTC, tombogle commented
We can probably just add to this PR for all the additional places. I had started working on this change a few weeks ago, but reigned it in as it was still unclear whether we were supposed to use "SIL Global" or the new (as yet undecided/unannounced) name for the "SCO" that will represent what was formerly sometimes called "International" (i.e., the part of SIL International that was not associated with a particular part of the world). Now it's clear that we should use SIL Global. The other thing that I think we need to do, however, is include UBS in the copyright statements as seen on the paratext.org website: **Copyright © 2024 SIL Global & United Bible Societies. All Rights Reserved.** (Not sure that the "All Rights Reserved" part is supposed to be included, though.)

2025-02-13 21:19 UTC, imnasnainaec commented
Subsumed in #209

2025-02-13 21:19 UTC, closed without merging